/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pujdgmkrangzamxiuflf";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1amRnbWtyYW5nemFteGl1ZmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5NTI1MjUsImV4cCI6MjA5MTUyODUyNX0.acO2NLZMUR5so3IgNCAyeGQvpSpkl9ZT--iG2Woy6mA";
